--------------------------------------------------------
--  File created - Thursday-November-22-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESULTS
--------------------------------------------------------

  CREATE TABLE "THESISADMIN"."RESULTS" 
   (	"ENVIRONMENT_ID" VARCHAR2(11 BYTE), 
	"CASE_ID" VARCHAR2(12 BYTE), 
	"ESTIMATED_TRAVEL_TIME" NUMBER(20,2), 
	"TRANSPORT_FARE" NUMBER(*,0), 
	"ACTION_NAME" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into THESISADMIN.RESULTS
SET DEFINE OFF;
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_68',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_70',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_72',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_74',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_76',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_62',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_64',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_66',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_53',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_55',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_57',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_59',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_45',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_47',37.56,14,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila and drop off at Arayat Cubao');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_47',1.5,0,'Walk towards Araneta Center-Cubao Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_47',6.72,13,'Ride the a train from Araneta Center-Cubao going to Taft Avenue Station and drop off at Ortigas Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_47',6.6,0,'Walk from Ortigas Station towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_49',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_51',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_38',37.56,14,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila and drop off at Arayat Cubao');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_38',1.5,0,'Walk towards Araneta Center-Cubao Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_38',6.72,13,'Ride the a train from Araneta Center-Cubao going to Taft Avenue Station and drop off at Ortigas Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_38',6.6,0,'Walk from Ortigas Station towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_40',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_42',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_44',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_31',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_33',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_35',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_37',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_24',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_26',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_28',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_15',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_17',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_19',37.56,14,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila and drop off at Arayat Cubao');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_19',1.5,0,'Walk towards Araneta Center-Cubao Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_19',6.72,13,'Ride the a train from Araneta Center-Cubao going to Taft Avenue Station and drop off at Ortigas Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_19',6.6,0,'Walk from Ortigas Station towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_21',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_7',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_9',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_11',37.56,14,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila and drop off at Arayat Cubao');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_11',1.5,0,'Walk towards Araneta Center-Cubao Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_11',6.72,13,'Ride the a train from Araneta Center-Cubao going to Taft Avenue Station and drop off at Ortigas Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_11',6.6,0,'Walk from Ortigas Station towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_13',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_0',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_2',37.56,14,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila and drop off at Arayat Cubao');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_2',1.5,0,'Walk towards Araneta Center-Cubao Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_2',6.72,13,'Ride the a train from Araneta Center-Cubao going to Taft Avenue Station and drop off at Ortigas Station');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_2',6.6,0,'Walk from Ortigas Station towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_4',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_6',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_79',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
Insert into THESISADMIN.RESULTS (ENVIRONMENT_ID,CASE_ID,ESTIMATED_TRAVEL_TIME,TRANSPORT_FARE,ACTION_NAME) values ('env_042','case_77',52.44,23,'Ride a Bus from UP Ayala Land Technohub going to Roxas Blvd / T. Claudio Intersection, Parañaque City, Manila  and drop off at Epifanio de los Santos Av and walk towards Asian Development Bank');
